# render.yaml

services:
  - type: web
    name: CVWOfrontend
    env: docker
    plan: free
    dockerfilePath: ./frontend/Dockerfile # Path to the frontend Dockerfile
    envVars:
      - key: REACT_APP_API_URL
        value: https://CVWObackend.onrender.com

  - type: web
    name: CVWObackend
    env: docker
    plan: free
    dockerfilePath: ./backend/Dockerfile # Path to the backend Dockerfile
    envVars:
      - key: PORT
        value: 8080

