# render.yaml

services:
  - type: web
    name: CVWOfrontend
    env: docker
    plan: free
    dockerfilePath: ./frontend/Dockerfile # Path to the frontend Dockerfile
    dockerContext: ./frontend
    routes:
      - type: rewrite
        source: /api/*
        destination: https://cvwobackend.onrender.com/*
    envVars:
      - key: REACT_APP_API_URL
        value: /api

  - type: web
    name: CVWObackend
    env: docker
    plan: free
    dockerfilePath: ./backend/Dockerfile # Path to the backend Dockerfile
    dockerContext: ./backend
    envVars:
      - key: PORT
        value: 8080

